### PR TITLE
Support for option82 fixes #3

### LINKED ISSUE #3: Option82
Please, can you add option82 field? I was find code example at this repo https://github.com/Olen/kea_hooks

### PR DESCRIPTION
**Pull request by funzoneq**
I needed support for Option82 as well, so I decided to add it. Fixes #3

### CODE REVIEW

**Comment by funzoneq** [comment]
@zorun please review.

**Comment by jgroom33** [comment]
@funzoneq looks like there's a conflict (from the option 60 merge probably)

**Comment by funzoneq** [comment]
@jgroom33 @zorun fixed the conflict.

**Comment by zorun** [comment]
Hi @funzoneq , the changes look good, I will try to test them soon.

Can you squash everything into a single commit with a descriptive commit message? Thanks!

**Comment by zorun** [comment]
@funzoneq it seems that you merged your branch again with master, so there's lots of unrelated changes and conflicts.

You need to rebase your changes on top of the current master. Or feel free to open a new PR if it's simpler.

**Comment by funzoneq** [comment]
@zorun I fixed the PR.

**Comment by zorun** [comment]
Sorry, I forgot about this PR. Thanks for updating it.

@funzoneq here is a review of the new code:

- you add support for options 12, 82, 43, can you separate each in a different commit and explain what is the purpose in each commit message?
- only option 82 is documented, can you add documentation for the other ones?
- why do you change the call to `getMAC()`, and is it related to support for the new options?
- it seems to me that you are storing binary data in env variables. Please switch to a hex-encoding format (using `toHexString()` instead of `toBinary()` or `toString()`), unless a DHCP option is known to contain a valid string; in that case, please add a comment stating this with a reference.

**Comment by funzoneq** [comment]
Hi @zorun. Thanks for the review, but this has been open for so long that I moved on. I will just keep my fork of the project. If you want the code, feel free to pull it in. If not, that's cool too.

**Pull request closed without merging**
